### ISSUE TITLE
Removal of Microsoft Edge Sidebar

### ISSUE THREAD

**Issue by timcrouse** [builtbybel/Winpilot#111]
The tool seems to have removed the option to toggle the Edge  side bar on-off.  After running the tool the side bar is gone as well as any option to enable it in the esettings.

**Comment by Belim** [comment]
the only thing that can be disable in this direction is "the big bing chat/Copilot button" in edge
![Bloatynosy_5vIT1wMchF](https://github.com/builtbybel/Bloatynosy/assets/57478606/1f882745-9671-491f-8281-a486baa3a9d4)
