### ISSUE TITLE
PC death (“Switch to Bloat-E”) ??? WHY IS THIS???

### ISSUE THREAD

**Issue by VitalCha05** [builtbybel/Winpilot#117]
…. So basically to describe this story. I used BN today to clean on an old laptop of mine. I’ve used this program a couple times now and it’s worked every time. I gave this laptop to a friend and he asked 30 minutes ago if he could use the program on his personal pc. He said he installed it and clicked the Bloat-E portion of the program. His PC crashed and won’t turn on. Why is this?

**Comment by Belim** [comment]
It is 101% not related to this application here.

**Comment by VitalCha05** [comment]
> It is 101% not related to this application here.

I’d not see how???? It’s your program 😂😂😂😂😂 Just curious honestly, bros pc dead
![IMG_6088](https://github.com/builtbybel/Bloatynosy/assets/153878315/14fa1e09-f9fd-4645-ba4a-5e70db880de0)
