### ISSUE TITLE
Add language options

### ISSUE THREAD

**Issue by a19901201** [builtbybel/Winpilot#124]
I hope that Chinese can be added and I can help translate into Traditional Chinese or Simplified Chinese.

**Comment by Belim** [comment]
yes, finally it can with this release https://github.com/builtbybel/Bloatynosy/releases/tag/2.0 🐱

**Comment by 171252** [comment]
Habe "German" bzw. "Translate" eingegeben, aber es bleibt in englisch.

**Comment by Belim** [comment]
Support for German is now available with the latest 3.0.5 version.

**Comment by 171252** [comment]
Thank you very much !!! 👍👍👍
