### ISSUE TITLE
How do i get microsoft store back?

### ISSUE THREAD

**Issue by dwi11415** [builtbybel/Winpilot#127]

**Comment by FreshImmuc** [comment]
1. Press Windows logo key + x

2. Select Windows PowerShell (Admin)

3. Select Yes

4. Copy and paste the command: Get-AppXPackage *WindowsStore* -AllUsers | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}

5. Press Enter

6. Restart your computer
