### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by Imborked** [builtbybel/Winpilot#145]
Why would you turn your app into the same kind of trash I use your app to get rid of? 

I just need a bloat remover, I don't need my bloat remover to also be bloated with the same trash I'm trying to remove from my windows installs.

**Comment by Iliano101** [comment]
The new UI really hinders the use of the app. I can't even figure out how to use the features of the original. Maybe I'm missing something, but this is now a different app with a different purpose that I no longer have a use for. Even just adding a menu to switch from the new app to the manual de-bloating of the old app would fix the problem.

**Comment by Broeckelmann** [comment]
Intuitive Usage is basically gone .-.

It was so easy beforehand, but now...

**Comment by ScottRFrost** [comment]
As an end-user I want to enable the full context menu.

Old bloaty nosy: Open System, double click Enable full context, click apply.

New bloaty nosy: Scroll down and look for option, can't find it, type in "context" to the dumb AI box, can't find it, type in "menu" to the dumb AI box, can't find it, give up, go back to old bloaty nosy.

GIANT step backwards in usability.

**Comment by Belim** [comment]
Hey guys, I know you can't please everyone, but the complaints were often present even in the last 1.x Bloatynosy Classic version in the issues here. Some cope with it, others don't. I will migrate all settings from Bloatynosy Classic to Winpilot. The current 3.05 version already brings a lot with it.

![Winpilot_VvUYtiXwk6](https://github.com/builtbybel/Winpilot/assets/57478606/ecd626f0-9b08-4c50-83fa-3ecff3b465e4)

**Comment by A9G-Data-Droid** [comment]
When I read the new README, my gut reaction was "y'all jumped the shark". I know, first impressions like this can be harsh but I have to agree with the general sentiment here. 

Let me be clear: WinPilot is cool. I like it for what it is but its' a separate product from BloatyNosy. If I want a debloater, I would use BloatyNosy. If I wanted an AI assistant who can change windows settings I would use WinPilot.

Even the fact that WinPilot can call upon Bloaty Nosy is cool. They just need to be kept separate.

Modular software is good. [To quote the old grey beards of Unix](https://en.wikipedia.org/wiki/Unix_philosophy):

> Make each program do one thing well. To do a new job, build afresh rather than complicate old programs by adding new "features".
> Expect the output of every program to become the input to another, as yet unknown, program. Don't clutter output with extraneous information. Avoid stringently columnar or binary input formats. Don't insist on interactive input.

**Comment by Belim** [comment]
> When I read the new README, my gut reaction was "y'all jumped the shark". I know, first impressions like this can be harsh but I have to agree with the general sentiment here.
> 
> Let me be clear: WinPilot is cool. I like it for what it is but its' a separate product from BloatyNosy. If I want a debloater, I would use BloatyNosy. If I wanted an AI assistant who can change windows settings I would use WinPilot.
> 
> Even the fact that WinPilot can call upon Bloaty Nosy is cool. They just need to be kept separate.
> 
> Modular software is good. [To quote the old grey beards of Unix](https://en.wikipedia.org/wiki/Unix_philosophy):
> 
> > Make each program do one thing well. To do a new job, build afresh rather than complicate old programs by adding new "features".
> > Expect the output of every program to become the input to another, as yet unknown, program. Don't clutter output with extraneous information. Avoid stringently columnar or binary input formats. Don't insist on interactive input.

Bloatynosy had become ingrained, and experienced users associated it with hardcore tuning and debloating. Over the past few months, I've addressed some of the issues, and today, I've closed them all. Many users either broke something or couldn't handle the functions. I had mixed feelings about it. You have no idea how many emails I received daily. I eventually shut down my email address. With Winpilot, I'm moving in a different direction, focusing on usability inspired by Microsoft. That's the way things are going. Microsoft is forcing the Copilot upon us; soon, even Auntie and Grandpa will know what it is and what it does because it will be present in every conceivable window and context menu. Winpilot shouldn't confuse users like Bloatynosy did because of its name; it should be clear what it does. Modeled after the Copilot, it guides Windows for the better and still offers smart debloating for the average user. The plugin CoTweaker encompasses almost all functions of Bloatynosy. What is missing here? Is it just the name? The plugin could also be called Bloatynosy... The first 5 plugins cover everything that Bloatynosy could do. The Assisted chatbox allows frequent settings adjustments to be made quickly without having to set checkboxes or move entries from one list to another, as in Bloatynosy.

**Comment by A9G-Data-Droid** [comment]
I apologize, I don't know the history. I'm just saying they are very different things. To me it's similar to "You want a car? Okay, here is the truck that delivers cars. Drive the truck to the your destination, park, and then unload the car you want from it". When before it was just a single car, the one people came here for.

If I want to debloat 10 computers, do I have to talk to an AI 10 times to do so? I would much prefer a tool that does one clear thing and is scriptable. Save your settings, apply your settings. It should be shipped as a single, stand-lone binary that doesn't need to be installed. Then it can be called by a login script with a settings file and apply the saved settings automatically.

This form factor could also be called by WinPilot. Some thing that both humans and AIs can enjoy.

**Comment by Belim** [comment]
That's all WinPilot can do and is more modular than Bloatynosy ever was. You can even teach the app your own commands and scripts. I still need to provide a small documentation for this. WinPilot is also portable and absolutely does not leave anything in the system except for a cache folder in the app's execution directory. Perhaps you should read the whole background https://builtbybel.com/blog/bloatynosy-is-now-winpilot

**Comment by Wolfhound905** [comment]
I miss the UX of thisiswin11

**Comment by LyndonGingerich** [comment]
Can Winpilot really do everything that BloatyNosy could? I remember seeing a lot more tweak options in BloatyNosy. And I'm not seeing a way to add plugins to Winpilot.

**Comment by Belim** [comment]
> Can Winpilot really do everything that BloatyNosy could? I remember seeing a lot more tweak options in BloatyNosy. And I'm not seeing a way to add plugins to Winpilot.

The staticAIData file in the apps directory supports dozens of skills, including executing PowerShell scripts, reg.exe commands, a plethora of command-line parameters, or integration with third-party tools. Indeed, the CoTweaker is still missing a few options from Bloatynosy, but I'll migrate those too. Do you have a specific one in mind?

**Comment by Belim** [comment]
Feel free to continue the [discussion](https://github.com/orgs/builtbybel/discussions) there
