### ISSUE TITLE
debloat misses several junk apps running (delayed start, hidden from registry, cmd lines etc)

### ISSUE THREAD

**Issue by ridingmower** [builtbybel/Winpilot#148]
the main check inside this code for running/background apps is based off the registry, however there are apps that are missed.

- [ ] Open an Admin Command Prompt and type "tasklist". You can also output this to a file by running "tasklist > c:\temp\list.txt"
- [ ] From PowerShell, run "Get-Process". Again, you can output this list to a file if needed.
- [ ] There are other apps that launch after delayed startup, that are hidden from the registry like HP etc.
- [ ] some apps are running under other windows services, this also need to be addressed in the roadmap

The code is missing and should account for those apps as well to debloat

<img width="736" alt="image" src="https://github.com/builtbybel/BloatynosyAI/assets/114959579/80bb1159-d579-4b32-8723-e1f408faf05e">

**Comment by Belim** [comment]
Bloatynosy has been renamed and completely redeveloped from the ground up. The project is now called [Winpilot](https://github.com/builtbybel/Winpilot/releases). This issue no longer exists here. Feel free to check it out if you'd like.
