### ISSUE TITLE
Decrapify: Some entries are listed twice

### ISSUE THREAD

**Issue by LyndonGingerich** [builtbybel/Winpilot#154]
![image](https://github.com/builtbybel/Winpilot/assets/84735110/1bafce4a-fe34-4486-abe0-a20e4643f200)

Clicking the second selects or deselects the first.

**Comment by Belim** [comment]
Yeah, you're right. I'll check that out soon. I'd actually noticed that before, but totally slipped my mind again. By the way, you're still using an outdated version, just FYI

**Comment by Belim** [comment]
I think I've fixed that in the latest release at https://github.com/builtbybel/Winpilot/releases/tag/3.2.5
Please give it a try.
