### ISSUE TITLE
Error loading crapware database

### ISSUE THREAD

**Issue by LyndonGingerich** [builtbybel/Winpilot#155]
![image](https://github.com/builtbybel/Winpilot/assets/84735110/0705342e-ca4c-41ff-a17b-76e4992a2e59)

Red text:
```
[!] Error loading crapware database: Could not find file 'C:\Windows\system32\app\appxData.json'.
Clippy says: I have found the following crapware. (If I present a false positive, please report it to my friend @Belim).
```

**Comment by Belim** [comment]
The appxData.json should be located within the app directory of the app itself. Have you unpacked the archive? Then, check if the file exists.

**Comment by LyndonGingerich** [comment]
Could not reproduce after installing latest release.
