### ISSUE TITLE
Move Clippy and his speech balloon behind Welcome to Winpilot dialog

### ISSUE THREAD

**Issue by LyndonGingerich** [builtbybel/Winpilot#158]
Showing me a dialog and then keeping me from reading it seems rude somehow.

![image](https://github.com/builtbybel/Winpilot/assets/84735110/22a29d53-1b06-4cf2-b7da-2b4524d1efbf)

**Comment by Belim** [comment]
Clippy is just a naughty boy 😹 . I can change it, but I wanted to draw attention to him right away. The welcome screen is also temporary and will disappear again.

**Comment by Belim** [comment]
https://github.com/builtbybel/Winpilot/releases/tag/3.3.0
