### ISSUE TITLE
Winpilot occasionally opens Windows Update

### ISSUE THREAD

**Issue by LyndonGingerich** [builtbybel/Winpilot#160]
When I return, I see this notification:
![image](https://github.com/builtbybel/Winpilot/assets/84735110/45908f19-519e-4ea7-ad40-86de08a4af1b)

**Comment by LyndonGingerich** [comment]
At the very least, I would like the choice whether to open Windows Update. If I'm not installing updates immediately, then I have to put up with regularly closing the Windows Update window while Winpilot is open.

**Comment by Belim** [comment]
The newer request has been addressed https://github.com/builtbybel/Winpilot/issues/188
