### ISSUE TITLE
Feature request: Ability to turn off Clippy

### ISSUE THREAD

**Issue by LyndonGingerich** [builtbybel/Winpilot#161]
Maybe a way to disable plugins?

**Comment by LyndonGingerich** [comment]
Okay, he apparently gives program messages. Could we at least have an option to turn off messages and actions not prompted by user action?

**Comment by namename-123** [comment]
Seconding this, it's just annoying.

**Comment by NicolaP8** [comment]
The only good thing of the original Clippy was that it was killable!
It's annoying, boring, useless, ugly.

**Comment by djashjones** [comment]
It was useless then and useless now!

**Comment by KyleStilkey** [comment]
I'd also like to add that the issue I have with it mostly is it's large and just in the way over menu icons. This should have a option to be removed.

**Comment by Belim** [comment]
Possible  https://github.com/builtbybel/Winpilot/releases/tag/2024.6.19
