### ISSUE TITLE
Decrapify appears to report crapware found when none is found

### ISSUE THREAD

**Issue by LyndonGingerich** [builtbybel/Winpilot#162]
Having red text in this response is confusing. Could we remove the red text if no crapware is found?

![image](https://github.com/builtbybel/Winpilot/assets/84735110/68825b84-a5ee-4e75-b70a-63a3039e3703)

**Comment by Belim** [comment]
Yeah, now that I see the picture, I always end up with totally different Clippy editions here 😬

**Comment by Belim** [comment]
https://github.com/builtbybel/Winpilot/releases/tag/3.3.0
