### ISSUE TITLE
Snipping tool not working

### ISSUE THREAD

**Issue by Anchovy1000** [builtbybel/Winpilot#168]
Snipping tool's shortcute (Win + Shift + s) was working perfectly fine until I installed winpilot and cleared my device of crapware and removed preinstalled microsoft programs. Is there any way to fix this

**Comment by Belim** [comment]
You might just need to close Winpiot. Are there any other screenshot tools you might be using that could potentially be using the same shortcut? Definitely not with Winpilot.

**Comment by Belim** [comment]
Have you uninstalled the snipping tool? Then simply reinstall it, what's the problem?

**Comment by Belim** [comment]
sry, can't replicate it to figure out what's going on

**Comment by Anchovy1000** [comment]
Sorry for not replying. No I'm not using any third party apps with the same shortcut, and I've reinstalled snipping tool many times. The shortcut just doesn't work anymore..

**Comment by Anchovy1000** [comment]
> sry, can't replicate it to figure out what's going on

Any third party apps you suggest?
