### ISSUE TITLE
Version 3.4 Triggers Windows Defender

### ISSUE THREAD

**Issue by CardcaptorRLH85** [builtbybel/Winpilot#172]
As said in the title, version 3.4 triggered three separate virus warnings in Windows Defender. Trojan:Script/Phonzy.B!ml in Winpilot.zip->app/backend.js, Trojan:Win32/Wacatac.B!ml in Winpilot.zip->Winpilot.exe, and Trojan:Script/Wacatac.H!ml in Winpilot.zip->app/frontend.html.  While I doubt that there's actually a trojan in these files, is there a way for you to submit to Microsoft so that your program doesn't get detected as a virus in the future?

**Comment by Belim** [comment]
Were already reported! What protection definition do you have?

**Comment by Belim** [comment]
Definitions updated.
