### ISSUE TITLE
Clippy should stop asking me to uninstall programs from the crapware list that I decided to keep

### ISSUE THREAD

**Issue by LyndonGingerich** [builtbybel/Winpilot#176]
I know I have them. I know Clippy doesn't like them. The same useless suggestion every time I get a status message grates on me.

**Comment by LyndonGingerich** [comment]
Besides, a misclick could uninstall something I don't want uninstalled.

**Comment by Belim** [comment]
Can agree, need to teach him 🥲

**Comment by LyndonGingerich** [comment]
Fixed in 3.5.0.
