### ISSUE TITLE
Copilotless search results should show in the screen, not in Clippy's speech balloon

### ISSUE THREAD

**Issue by LyndonGingerich** [builtbybel/Winpilot#177]
Currently, the entire Copilotless screen's use is one button, and that button feels unnecessary.

I still think that Copilotless should be merged into Decrapify...

**Comment by Belim** [comment]
Good one, the current solution isn't really vibing with me. I'll give it another glance. Thanks for all the pro tips 😃

**Comment by LyndonGingerich** [comment]
Gone in 3.5.0.
