### ISSUE TITLE
Handling of profiles

### ISSUE THREAD

**Issue by metafarion** [builtbybel/Winpilot#18]
I'm trying to set up a system where I can run just the fixes I want on a series of PCs.  I've exported a profile, but I'm not quite understanding the import process.

Importing a profile seems to just highlight the affected settings, but it doesn't actually change which boxes are checked, which makes it look like I still have to go down the list and click uncheck all the boxes I don't want.  If I Analyze after loading a profile, it actually unchecks ONLY the boxes I wanted checked, and colors the remaining items in red.  The meaning of both of these changes isn't clear in the UI.

Can you help me understand what is happening?  How is the Import Profile function supposed to work?

**Comment by Belim** [comment]
Could you please try the latest build once https://github.com/builtbybel/BloatyNosy/releases/tag/0.43.0? Here you can load a predefined profile, which automatically performs an analysis. Finally, you just need to click on "fix".

**Comment by metafarion** [comment]
Ok, I checked back on this, now trying version 0.85.0..... and I'm still confused.

Here is a slice of my saved profile after importing it.
![image](https://github.com/builtbybel/BloatyNosy/assets/2903603/14915a85-24c7-489c-b25a-91b1615e1b11)
The program has correctly highlighted my selections from the imported profile in yellow, however EVERY checkbox is still checked, so I don't understand what the Fix button is going to do when I click it.  It looks as though it may just run all the fixes, regardless of what my profile said to fix.

**Comment by huyz** [comment]
I'm even more confused.  I exported a profile.  And I can't figure out a way to import it.  Neither `Select a profile` nor `Load Profile` let me do anything.

**Comment by Belim** [comment]
I would recommend leaving Bloatynosy Classic behind and giving the rebranding and new development,  [Winpilot](https://github.com/builtbybel/Winpilot/releases), a chance. There won't be such usability issues here anymore.

**Comment by huyz** [comment]
Sorry I gave up entirely. All the constant renaming, rebranding, and changes have been unsettling for me. Plus, having AI in an app which I wanted to use to debloat the AI out of Windows? Too ironic for my taste :)
