### ISSUE TITLE
Can't refresh Clippy's speech balloon

### ISSUE THREAD

**Issue by LyndonGingerich** [builtbybel/Winpilot#182]
Error:
`Error loading questions in staticAIData from JSON: Could not find file 'C:\Windows\system32\app\staticAIData.json'.`

![image](https://github.com/builtbybel/Winpilot/assets/84735110/31c4c887-69f7-4573-b140-44ddd8aa152d)

**Comment by Belim** [comment]
I had already written it [here(https://github.com/builtbybel/Winpilot/issues/184). You might want to consider downloading the app again and unpacking everything onto the desktop to check if the said JSON file is present in the app directory.

**Comment by LyndonGingerich** [comment]
Fixed in 3.5.0.
