### ISSUE TITLE
Clippy's suggestions are not left-aligned

### ISSUE THREAD

**Issue by LyndonGingerich** [builtbybel/Winpilot#184]
![image](https://github.com/builtbybel/Winpilot/assets/84735110/00ef94f4-57a9-485a-b753-2b1a7e07271a)

**Comment by LyndonGingerich** [comment]
System32? No, I use it straight in the Downloads folder. Is Winpilot not portable anymore?

**Comment by LyndonGingerich** [comment]
Winpilot shouldn't depend on install location, should it?

**Comment by Belim** [comment]
Of course, completely portable. But in the error message, the file is being searched for in the sys32 directory. It looks like you might have extracted it there.

**Comment by Belim** [comment]
The important thing is to extract the archive, where you extract it doesn't really matter, but please avoid system directories. After extracting, you should see a folder named 'app.' In there, you'll find the staticAIData.json file among other things. If this file is missing, then the archive isn't complete or is corrupted. In that case, please download it again.

**Comment by LyndonGingerich** [comment]
I didn't put anything in a system directory; I downloaded and extracted just recently and distinctly remember that that's all I did. Downloading and extracting again worked, though.

But the suggestions still aren't left-aligned.

**Comment by Belim** [comment]
Please check if the file staticAIData.json exists in the app directory!

**Comment by LyndonGingerich** [comment]
It does, but I emphasize: I didn't mess with the files. If there is a problem with the extracted files, then either something messed with them without my knowledge--which I don't think I have anything set up to do--or there's a bug in the bit of Winpilot that handles those files.

**Comment by Belim** [comment]
Thanks, can you search for Titus (Tool) or perform other static search queries? If yes, then it's working now without any reason. There have been no complaints until today, but I will optimize the file transfer process a bit more

**Comment by atdale** [comment]
I am receiving the same message, but the app folder path in the error message is a different path than the app folder's location. The app folder path is: ""C:\Users\XXXXX\Github\winpilot\app". The message notes that Winpilot is looking for the file in the app folder at: ""C:\Windows\System32\app" However, there is no app folder in the System directory.

**Comment by Belim** [comment]
Could you please test with this build?
[Winpilot_dev.zip](https://github.com/builtbybel/Winpilot/files/14954621/Winpilot_dev.zip)

**Comment by LyndonGingerich** [comment]
Fixed in 3.5.0.
