### ISSUE TITLE
Welcome text is far too long

### ISSUE THREAD

**Issue by LyndonGingerich** [builtbybel/Winpilot#185]
Current text:
> Winpilot is the next evolution of Bloatynosy. You can navigate through WinPilot's step-by-step assistant and the 'Back' and 'Next' buttons to debloat your Windows system, Lenovo Legion Go and ROG Ally and tailor it to your desires. Alternatively, you can use this AI chatbox to perform system actions. Throughout the entire process, your assistant is Clippy. He keeps you updated on the status of your actions and occasionally throws in a witty remark or two.

No one is going to read that. I still haven't read it all the way through. I just open Winpilot and look for the plugin menu.

**Comment by Belim** [comment]
That had been bothering me as well, so I took some time yesterday to rewrite it a bit

![Winpilot_fBlSsyium6](https://github.com/builtbybel/Winpilot/assets/57478606/ea9596de-6579-410e-b5ae-0cca7ccdc0ce)

**Comment by LyndonGingerich** [comment]
My recommendation for the Welcome screen:
- Title: Winpilot
- Search box, with text of "Ask the AI" or "Command the AI" or something
- Bottom left: "Start" button, replacing the current "Next" button (invalid "Back" button removed)
- "Pilot" button renamed to "Modules"
- No welcome paragraph at all

If you must, you could add a subtitle of "The next evolution of Bloatynosy", which replaces the first sentence. Needing to explain the three workflows (AI-based, step-by-step, and using individual plugins) just means that the buttons themselves aren't clear enough, so clarify them and remove that bit. The Lenovo Legion Go and ROG Ally run Windows 11, so people will assume that Winpilot works on them unless otherwise stated, so cut that bit. That leaves no introductory text necessary.

**Comment by Belim** [comment]
https://github.com/builtbybel/Winpilot/releases/tag/2024.4.7
