### ISSUE TITLE
Refresh button shows an error from Clippy

### ISSUE THREAD

**Issue by LyndonGingerich** [builtbybel/Winpilot#186]
https://github.com/builtbybel/Winpilot/assets/84735110/7831dad6-95bc-499a-b260-0433c30441bb

I'm still not sure exactly what the Refresh button is supposed to do, but presumably it shouldn't show an error.

**Comment by Belim** [comment]
Check https://github.com/builtbybel/Winpilot/issues/184

**Comment by LyndonGingerich** [comment]
Fixed in 3.5.0.
