### ISSUE TITLE
First Start - System cannot find File

### ISSUE THREAD

**Issue by Memphiisto** [builtbybel/Winpilot#191]
Hi!
I just installed a fresh windows 10 and installed all Updates.
Updated the Windows APP Installer.
But i still get the error: System cannot find file (HRESULT: 0x80070002)

Anything i can do?

Thanks!
![image](https://github.com/builtbybel/Winpilot/assets/42480691/b76d4fe0-93e2-41af-be09-8957eeb4e595)

**Comment by Belim** [comment]
Is the Edge Runtime installed on your system? If not, simply download the Evergreen Bootstrapper https://developer.microsoft.com/microsoft-edge/webview2/?form=MA13LH#download
