### ISSUE TITLE
How do I Disable the mod AutoLogon? There is no way to disable it in the winpilot

### ISSUE THREAD

**Issue by AayushV12** [builtbybel/Winpilot#193]
How do I Disable the mod AutoLogon? There is no way to disable it in the app.

**Comment by Belim** [comment]
External scripts/plugins in the extensions area cannot all be individually reverted. For example, the autologon script can be reverted in this way. 

Click Start, and then click Run.
- In the Open box, type Regedit.exe, and then press Enter.
- Locate the HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon subkey in the registry.
- Double-click the AutoAdminLogon entry.
- In the Edit String dialog box, change the value to 0 and then click OK.
https://learn.microsoft.com/en-us/answers/questions/1379921/how-to-temporarily-disable-autologon-setup-with-sy

**Comment by Belim** [comment]
External scripts/plugins in the extensions area cannot all be individually reverted. For example, the autologon script can be reverted in this way. 

Sol,
https://learn.microsoft.com/en-us/answers/questions/1379921/how-to-temporarily-disable-autologon-setup-with-sy
