### ISSUE TITLE
No UI

### ISSUE THREAD

**Issue by thesamim** [builtbybel/Winpilot#204]
I ran WinPilot on my laptop just fine last night.

This what I get on my desktop:
![image](https://github.com/builtbybel/Winpilot/assets/5315625/5a7a1fc3-ddda-406e-a9fc-6579495c9934)

Troubleshooting steps please?

**Comment by Belim** [comment]
Could you please check if the content of the app directory includes all these files?
![explorer_EIWWVnmXkd](https://github.com/builtbybel/Winpilot/assets/57478606/9156f4d4-d818-4613-bc7e-5cc18eab4435)

**Comment by RisheekKandoi** [comment]
Hi @Belim , I was facing the same issue. Pls try extracting the files before launching the application. This worked for me :)

**Comment by thesamim** [comment]
Thanks.

Re-downloaded, re-extracted, re-ran, all is well.
