### ISSUE TITLE
Winpilot Error create data directory 

### ISSUE THREAD

**Issue by mypockets** [builtbybel/Winpilot#212]
When I try to run Winpilot I receive the following error.

We couldn't create the data directory.
Microsoft Edge can't read and write to its data directory:
C:\Program Files\Utilities\Winpilot\Winpilot.exe.WebView2\EBWebView

**Comment by mypockets** [comment]
[Winpilot Errors.pdf](https://github.com/builtbybel/Winpilot/files/15433270/Winpilot.Errors.pdf)

**Comment by Belim** [comment]
Try launching the app from a different location, like the desktop. It seems the app's cache folder can't be created due to missing directory permissions. If that doesn't work, please check also this https://github.com/builtbybel/Winpilot/issues/191
