### ISSUE TITLE
clippy blocks bottom functionality in app

### ISSUE THREAD

**Issue by aaronwi** [builtbybel/Winpilot#215]
![image](https://github.com/builtbybel/Winpilot/assets/5341699/65fca50d-a2c0-4492-85fb-4a515cec9398)

not sure if this was intentional, but it blocks actual functionality of the app

could be resolved by adding a buffer space to scroll down further

**Comment by Belim** [comment]
Ive been working for a few days on separating the Clippy bubble from the assisted actions. I'll roll out the update soon, today, and hopefully, Clippy will then be perceived as less intrusive
