### ISSUE TITLE
Possible interference with windows hello and fingerprint scanner?

### ISSUE THREAD

**Issue by quartzbear** [builtbybel/Winpilot#24]
**Edit**: NVM, found the setting. Why would you want to disable biometrics? the fingerprint scanner isn't secure enough?

Hi

I really appreceate your work on these projects.

I set up the computer, with a fingerprint scanner to login.
Installed BloatyNosy from Microsoft Store, and everything went well.
I just noticed that the fingerprint scanner stopped working.
Any Idea which setting or removed software could cause that?

thanks

**Comment by Belim** [comment]
Indeed, it does not seem to be integrated in a meaningful way anymore. I will remove this function in one of the upcoming versions. I have also noticed [numerous issues in this regard on ThisIsWin11](https://github.com/builtbybel/ThisIsWin11/issues?q=is%3Aissue+is%3Aopen+biometrics).

Thank you.

**Comment by quartzbear** [comment]
Thanks!
