### ISSUE TITLE
Turn Search in Settings back on

### ISSUE THREAD

**Issue by Reuzehagel** [builtbybel/Winpilot#31]
Is it possible to revert this option without restoring everything back to how it was?

**Comment by Reuzehagel** [comment]
It seems to be disabled even after restoring to defaults.

**Comment by Reuzehagel** [comment]
It seems to stay disabled even after restoring to default.

**Comment by Reuzehagel** [comment]
![image](https://user-images.githubusercontent.com/105865503/233958541-0ec1a590-552d-4be2-baa7-391d8fca0443.png)
I mean this. Is there any way to enable it again?

**Comment by Belim** [comment]
It should be easily restored with just one click, even with Bloatynosy Classic. However, the rebranded [Winpilot](https://github.com/builtbybel/Winpilot/releases) no longer handles this option.
