### ISSUE TITLE
Clicking Settings icon freezes program

### ISSUE THREAD

**Issue by LyndonGingerich** [builtbybel/Winpilot#32]
Whenever I click Settings, BloatyNosy freezes for a while, then finally pops up Settings. I'm running version 0.43.70 on Windows 11 Pro, Version 10.0.22621, Build 22621.

BloatyNosy is well worth the conscience donation to upgrade from BloatBox. I love the settings optimization. I had given up hope on uninstalling Widgets (though it took a few attempts with BloatyNosy).

**Comment by Belim** [comment]
Is there a permanent internet connection?

**Comment by LyndonGingerich** [comment]
Yes, there is.

**Comment by Belim** [comment]
Give the successor to Bloatynosy, [Winpilot](https://github.com/builtbybel/Winpilot/releases), a shot.
