### ISSUE TITLE
InstaPackage not available from latest GitHub release when Microsoft Store version also installed

### ISSUE THREAD

**Issue by LyndonGingerich** [builtbybel/Winpilot#33]
I get this pop-up when I go to InstaPackage from the latest GitHub release (0.43.70) if I have previously installed the version from the Microsoft Store. I'm running version 0.43.70 on Windows 11 Pro, Version 10.0.22621, Build 22621.

![image](https://user-images.githubusercontent.com/84735110/233095905-b95cadc3-625d-4074-9e00-2789d0097517.png)

**Comment by LyndonGingerich** [comment]
Uninstalling the store version worked. But shouldn't I be able to use one with the other installed? If not, we can close this issue.

**Comment by LyndonGingerich** [comment]
Now that [BloatyNosy has been banned from the Microsoft Store](https://github.com/builtbybel/BloatyNosy/releases/tag/0.60.0), is this feature obsolete?

**Comment by Belim** [comment]
Yes, Feature removed, [Winpilot](https://github.com/builtbybel/Winpilot/releases) is here.
