### ISSUE TITLE
re enabling widgets doesn't work and it seems restoring isn't helping too. Please help

### ISSUE THREAD

**Issue by krrishnix** [builtbybel/Winpilot#37]
i disabled my widgets by mistake. using the restore feature I try re enabling the widgets, and after completion it shows the message that widgets have been enabled but i cannot see it on my taskbar. i went to taskbar settings, the option wasn't there neither there was any help after restarting. Please help.

**Comment by Belim** [comment]
Translate to English: I guess you completely uninstalled the widgets feature. Search for the entry "Desktop [MIDDLE] Uninstall Widgets feature" and initiate a restore. The Microsoft Store will open. Install the Windows Web Experience Pack from there.

**Comment by Belim** [comment]
I guess you completely uninstalled the widgets feature. Search for the entry "Desktop [MIDDLE] Uninstall Widgets feature" and initiate a restore. The Microsoft Store will open. Install the Windows Web Experience Pack from there.

**Comment by Mirm0n** [comment]
I'm having the same issue. But the widget button is back, but it doesn't work and it doesn't show the weather like it used to. I did the restore from the bloaty app but it doesn't do anything. @Belim The microsoft store doesn't open on it's own and I don't find the windows web experience pack

**Comment by Mirm0n** [comment]
I figured it out!!

Follow these steps:
Got to this link and install  Windows Web Experience Pack
https://apps.microsoft.com/store/detail/windows-web-experience-pack/9MSSGKG348SP?hl=en-us&gl=us

If it doesn't show an install button then it means it already installed.

In that case you should uninstall it first by opening cmd as adminstrator and type:

winget uninstall "windows web experience pack"


Then go back to the link and reinstall it.

Last step: go to windows task manager and restart your file explorer.
