### ISSUE TITLE
Analyse list all setting to be change/mod

### ISSUE THREAD

**Issue by docop** [builtbybel/Winpilot#38]
Hi
 I wonder if it could be possible to get a button like : Analyse , before applying a fix and not knowing what it will do. Or change setting... A dual warning message could be perhaps also put as a notification when only 1 click <fix> is press.
Thanks

**Comment by Belim** [comment]
Winmodder is no longer part of the new development.   Give the successor to Bloatynosy, [Winpilot](https://github.com/builtbybel/Winpilot/releases), a shot.
