### ISSUE TITLE
"Get Started" not getting removed (BN 0.80)

### ISSUE THREAD

**Issue by kajoken** [builtbybel/Winpilot#47]
Hello.

First I'd like to thank you for this wonderful tool. It's a good thing we can remove all this bloatware so easily.

For my issue, for some reason I cannot remove the "Get Started" and "Skype" Apps from my system. I'm using the newest beta 0.70.54.

When I use the fix feature BN tells me, that the apps are all successfully removed,

- Uninstalling Microsoft.Getstarted
App removed Microsoft.Getstarted
- Uninstalling Microsoft.SkypeApp
App removed Microsoft.SkypeApp

but even after a reboot it's still there in my start menu and can be started normally. All other listed apps seem to be removed successfully.

OS: Windows 11 Pro
Version: 10.0.22621 Build 22621

Thanks in advance. :)

**Comment by Vipin2003** [comment]
I think that they can't be removed...I also tried with every possible method..but no soution.

**Comment by kajoken** [comment]
Yeah, the newest version 0.80 still can't remove "Get Started". Looks like it's just not possible. 
Skype on the other hand is gone. Probably was an bug on my site then.

And god I wish they'd stop recommending WSL. I don't want that on by default. It's a Bloatware Remover not a Bloatware Adder.

**Comment by Belim** [comment]
Yup, not possible. I could make it possible, but I don't want to, not even with the successor, [Winpilot](https://github.com/builtbybel/Winpilot/releases).
