### ISSUE TITLE
New desktop ->New instance of an app - this feature of the Win11 got deleted- please help!

### ISSUE THREAD

**Issue by jdp88** [builtbybel/Winpilot#56]
Namaskar, 

I used BloatyNosy for deleting bloatware and annoying widgets. Now its a breeze of cool air.  Joy of having a lot simpler UI. 

     But I am missing one feature of Win 11. That is, when we have multiple desktops open, when you click on the app icon on taskbar it will start new instance of that app in the same desktop. But now after running BloatyNosy, whenever I click on an app icon on the taskbar it switches to the desktop it's currently running in. Can this be reversed to the original setting, I need it a lot. 

Thanks in advance for your attention.

**Comment by Belim** [comment]
Give the successor to Bloatynosy, [Winpilot](https://github.com/builtbybel/Winpilot/releases), a shot.
