### ISSUE TITLE
Webcam doesn't work anymore

### ISSUE THREAD

**Issue by romain145** [builtbybel/Winpilot#62]
Camera is not working anymore in any app.
In the Settings menu Bluetooth & devices > Cameras > HP Webcam 1300, the preview is only showing grey:

![image](https://github.com/builtbybel/BloatyNosy/assets/4060945/893b9cf0-0a1c-4405-a1c9-ede4058dd2c3)

Any idea what's happening?

**Comment by Muccle** [comment]
have the same problem. after running bloatynose (great tool, thank you very much!)  camera shows nothing anymore. which setting i have to recover to make it working again?

**Comment by Belim** [comment]
Simply reactivate app access to the camera. The feature is no longer available with the rebranding and [Winpilot](https://github.com/builtbybel/Winpilot/releases) anyway.
