### ISSUE TITLE
'Restore Default' is misleading

### ISSUE THREAD

**Issue by KaitlynEthylia** [builtbybel/Winpilot#64]
Using the restore defaults button doesn't return your registry to the state it was in before the programme was used, it simply sets things to the opposite of what they were, this is a deal breaker for me, is there any possibility of this changing?

**Comment by Her0es** [comment]
> Using the restore defaults button doesn't return your registry to the state it was in before the programme was used, it simply sets things to the opposite of what they were, this is a deal breaker for me, is there any possibility of this changing?

Where did you see this restore default option?

**Comment by Belim** [comment]
The successor [Winpilot](https://github.com/builtbybel/Winpilot/releases) handles things completely differently and is a breeze to use.
