### ISSUE TITLE
Windows "Some of these settings are managed by your organization" message

### ISSUE THREAD

**Issue by sidsharths1245** [builtbybel/Winpilot#65]
First the message appeared in my browser, I freaked out and reset my PC and all the passwords thinking I had gotten a malware. After the fresh install when I ran this app again, this time the warning appeared in the systems privacy settings. Is there a way to disable/revert this? It seems the app applies some kind of group policy/registry tweak or something.

![image](https://github.com/builtbybel/BloatyNosy/assets/64619769/28c78728-b3db-4cf7-a42d-c8e6f330998b)

**Comment by ltptnt** [comment]
Unfortunately, no. This program uses the registry to change the privacy settings on a machine. I don't believe there is any way of removing these "Some of these settings are managed by your organization" messages and to revert these settings you would need to revert them through the BloatyNosy software.

**Comment by optisynapsis** [comment]
Same here, fully reinstalled windows after thinking some obscure malware had got me lol. (Probably needed it though eh). 
Later realised it may have been this app, since the message occured after a reinstall and in both chrome and edge. 

Is it possible to revert them through bloatynosy? I can't see an otion to do this in the app. 

Could the registry entries in question be posted here?

**Comment by Her0es** [comment]
> Same here, fully reinstalled windows after thinking some obscure malware had got me lol. (Probably needed it though eh). Later realised it may have been this app, since the message occured after a reinstall and in both chrome and edge.
> 
> Is it possible to revert them through bloatynosy? I can't see an otion to do this in the app.
> 
> Could the registry entries in question be posted here?
> 
> (Also, might be worth considering warning users about this. Even as an advanced user, this is a difficult one to pin down the origin of).

This. Would also like a warning on that the app would show this in the settings.

**Comment by stalingino** [comment]
Can be managed by editing registry under [Computer\HKEY_CURRENT_USER\Software\Policies\Microsoft\Edge]
and these policies can be reloaded from edge://policy

I needed only these policies enabled: 
AutofillAddressEnabled
LocalProvidersEnabled

**Comment by Belim** [comment]
The successor [Winpilot](https://github.com/builtbybel/Winpilot/releases) only tracks settings of the currently logged-in user. These notifications are now a thing of the past.
