### ISSUE TITLE
Problems with running as a User that does not have admin rights

### ISSUE THREAD

**Issue by rtl19** [builtbybel/Winpilot#73]
This tool looks great.  When running as an Admin user, it worked well.  I then tried to run it as a limited user and it could not uninstall the bloat for that user.  It would just error out at each attempt to uninstall an item.  I assume if I ran it under the limited user but with admin rights, it would just perform it's actions against the admin user instead of the limited user.

Use case: This PC is used by multiple people.  The Windows bloat repeats for each limited user so it seems like we'll need to run bloatynosy for each limited user.

**Comment by Belim** [comment]
Appx packages are only removed for the currently logged-in user. That was the case with Bloatynosy and behaves similarly with its successor, [Winpilot](https://github.com/builtbybel/Winpilot/releases). You could give it a try and report back.
