### ISSUE TITLE
When scanning the exefile, it gives a possitive response as a trojan

### ISSUE THREAD

**Issue by Rolami** [builtbybel/Winpilot#76]
https://www.virustotal.com/gui/file/b8a178dd0b8397892bdabf78410962c7ae368330bfda1edb25443c8046777bbb

Check the link for mor info.

**Comment by p1ns** [comment]
> https://www.virustotal.com/gui/file/b8a178dd0b8397892bdabf78410962c7ae368330bfda1edb25443c8046777bbb
> 
> Check the link for mor info.

This is because the application changes critical Windows settings. That's why apps like Defender removers and activators are also detected as Trojans. False positive.

**Comment by THFourteen** [comment]
Same here, showing two results as a trojan for me 
https://www.virustotal.com/gui/file/ce5bdbccd54498fd07df246b2983a6451238966980602a617c6f8a745909fb10

Windows Defender has also got itself tied in nots as i've deleted the file but it thinks its still there.

![image](https://github.com/builtbybel/Bloatynosy/assets/1321575/f6a62891-e62b-4915-9826-7026bef186a3)
