### ISSUE TITLE
Admin Mode won't work with a few Features

### ISSUE THREAD

**Issue by DigitalNXZ** [builtbybel/Winpilot#77]
"Could not start C:\Users\xxx\AppData\Local\Microsoft\WindowsApps\wt.exe winget uninstall "windows web experience pack" --silent." in Admin mode.

i created a Admin acc and a non admin account, and somehow on both profiles when i start bloatynosy in normal mode it seems to open powershell.. but in Admin? nothing at all happens.

now did microsoft change a few things? it also is also very hard to remove all ms apps on my admin acc with the chris titus tool.. and the apps are still there?! or is my system broke? somehow no debloat tool works right anymore? i know it worked 1 month ago?

same with remove one drive cloud?.. it deleted it somehow but still detected it, i had to remove the folder so it detects it as "gone" 🤔

but i can start powershell in admin-mode myself and do winget uninstall "xx"?

**Comment by Belim** [comment]
Give the successor to Bloatynosy, [Winpilot](https://github.com/builtbybel/Winpilot/releases), a shot.
