### ISSUE TITLE
Restore Scan & Fax Printer

### ISSUE THREAD

**Issue by DigitalNXZ** [builtbybel/Winpilot#78]
(Remove Fax Printer) states it cannot be undone, if i'm rights it deletes the wfs.exe? this was missing for me, after using BloatyNosy
if yes, there is: dism /Online /Add-Capability /CapabilityName:Print.Fax.Scan~~~~0.0.1.0 
installs the feature, idk how safe it is.. but i hope it helps somehow :)

found it in the ms forum ([source](https://answers.microsoft.com/en-us/windows/forum/all/windows-fax-scan-mistakenly-uninstalled-how-to/ad9f7216-3b65-4b3f-8991-4a6958f89d12)), worked well for me.

**Comment by Belim** [comment]
Thank you. That could potentially be included in the successor, [Winpilot](https://github.com/builtbybel/Winpilot/releases)"
