### ISSUE TITLE
Reenabling Game DVR Feature leaves the GP policy at Not Configured

### ISSUE THREAD

**Issue by Seefer** [builtbybel/Winpilot#86]
I disabled Game DVR for Windows 11 but later decided to enable it but there were issues in that the Record and Screenshot buttons were always greyed out for every game. No amount of Repair or Reset of the app in Windows 11 App Settings got this to work so I checked **Windows Game Recording and Broadcasting** component using **gpedit** and found it was set to **Not Configured**. I had to set this to **Enabled** for Game DVR to function normally. Is this intended behavior when reenabling a Windows feature disabled with BloatyNosey? I feel that this component's group policy should be set to **Enabled** in order to restore functionality.

**Comment by Foul-Tarnished** [comment]
yes this tool is garbage, the default are stupid

and I unticked the disable game dvr, and it still did it, and I had to edit registry myself, bc the revert thing didn't work

**Comment by ryanmusante** [comment]
It's not garbage. It's a great tool with some quirks to iron out.

**Comment by Belim** [comment]
Give the successor to Bloatynosy, [Winpilot](https://github.com/builtbybel/Winpilot/releases), a shot.
