### ISSUE TITLE
Logitech+ options

### ISSUE THREAD

**Issue by se7en2wo6ix** [builtbybel/Winpilot#88]

**Comment by se7en2wo6ix** [comment]
I am not able to install logitech+ options after using bloatynosy... ia m not sure it is happening because of your scriot or because of ChrisTitusTechwinutil..... if possible guide me .

**Comment by Belim** [comment]
I'd say let's rule out Bloatynosy for now. Give the successor to Bloatynosy, [Winpilot](https://github.com/builtbybel/Winpilot/releases), a shot.
