### ISSUE TITLE
Thank you, this software is awesome and I was wondering...

### ISSUE THREAD

**Issue by Wateraga** [builtbybel/Winpilot#9]
Is there a way to batch script for the WinModder Mods/Plugins page?
Also how do I add more programs to the InstaPackage page?

You have already condensed about 10+ apps I've tried to use in the past to do what your apps do with 2, If I could possibly customise it further it would save me so much trouble when it comes to installing/reinstalling Windows and finally having a shortcut way to have a customiseble Windows setup. 

Lastly I know it's not the same app but you develop CloneApp too, how do I add my own apps to the CloneApp list along with the locations for important data for them?

I understand you may not be able to advise me how to do any/all of this but it would be greatly appreciated if you could help me in any way. I've spent a long time trying to find *my* perfect way of setting windows up and installing particular software with particular setups ie themes/plugins/custom data locations etc.

Thank you so much for these apps, they do exactly what they need to do and do it well. I am currently a beginner coder and am hoping to contribute more in the future, you have filled my head with ideas that I can't implement but has given me a boost to continue my Python course with entheusiasm.. at the very least I could send you any locations for data for the apps that I add to the CloneApp list, would be happy to add to an already awesome app.

**Comment by Belim** [comment]
> Is there a way to batch script for the WinModder Mods/Plugins page?
> Also how do I add more programs to the InstaPackage page?

Check in build 0.32 the WinModder page and the "Offline packages template for Instapackge" 😃

**Comment by Wateraga** [comment]
> > Is there a way to batch script for the WinModder Mods/Plugins page?
> > Also how do I add more programs to the InstaPackage page?
> 
> Check in build 0.32 the WinModder page and the "Offline packages template for Instapackge" 😃

Okay that all sounds really good and thank you so much for your work..

So I checked out the Winmodder page and it's no different for me, I did notice the "Export Profile" option though on the main page, will that include and changes mdae to the WinModder page?

Also since I changed from v0.2.1 I haven't been able to use the MajorGeeks Mod pack "https://www.majorgeeks.com/mg/sortname/majorgeeks_registry_batch_file_tweaks.html".
It was easy to add in v0.2.1 but since then I haven't been able to get them to show in the Debloos/BloatyNosy app, any ideas how to fix that?

Also it may just be me being stupid but I can not get any new apps to show on the InstaApps page, none of the previous versions worked either but currently using the new v0.32.0 and it doesn't create a packages.txt, I added the one I had from a previous version to the BloatyNosy app folder but still can't get any to show. For example trying to add Quicklook or Notepadsapp and neither will show in the list of apps.

Thank you for your time with this app it's a really great piece of software and is getting better each update!

**Comment by jimbrig** [comment]
> Lastly I know it's not the same app but you develop CloneApp too, how do I add my own apps to the CloneApp list along with the locations for important data for them?

@Belim and @Wateraga I agree with this idea/enhancement as well. Honestly, CloneApp (and UA) is probably the most underrated Windows application on GitHub I’ve come across simply from the knowledge regarding a variety of applications  and their full impact on a Windows OS. 

Although this would be better suited as an issue in that repo.

@Belim would you be willing to share some of your notes or documentation on the technical implementation side of these projects?

—-

PS: 


> I've spent a long time trying to find *my* perfect way of setting windows up and installing particular software with particular setups ie themes/plugins/custom data locations etc.

Amen. The never ending struggle

**Comment by Belim** [comment]
I have completely redesigned CloneApp. You can find the new project, [Appcopier](https://github.com/builtbybel/Appcopier), here. "I am no longer developing CloneApp. Unfortunately, it was still a VB6 project, and I doubt anyone would want to continue it, even though I am [willing to release the source code](https://github.com/builtbybel/CloneApp/releases/tag/2.15.606).

**Comment by Wateraga** [comment]
> I have completely redesigned CloneApp. You can find the new project, [Appcopier](https://github.com/builtbybel/Appcopier), here. I am no longer developing CloneApp. Unfortunately, it was still a VB6 project, and I doubt anyone would want to continue it, even though I am [willing to release the source code](https://github.com/builtbybel/CloneApp/releases/tag/2.15.606).

Fire 🔥 Will try it later today. Appreciate the hard work mate!
