### ISSUE TITLE
How to solve errors with Winget. (eg. uninstall Windows Web Experience Pack)

### ISSUE THREAD

**Issue by ThinkEV** [builtbybel/Winpilot#91]
On a fresh windows 11 installation (winget -v reports version 1.2.10691) I am getting winget uninstall errors. Actually, it does not work at all. 

The solution is to update winget.

1. Open `https://aka.ms/getwinget` which downloads the latest version, e.g. Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle

Installing it by just calling the file fails. You need to install it with PowerShell like this:

2. Open PowerShell as Administrator
3. Type: `Add-AppPackage -path "C:\Users\YOUR-USERNAME\Downloads\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle"`

This will install it. Enjoy.

**Comment by freddyboy1974** [comment]
Go to Store app in Windows. Search Winget, Update from there.

**Comment by ThinkEV** [comment]
This did not work on my machine: it was denied with an error message. The way I described always works.

**Comment by Belim** [comment]
Give the successor to Bloatynosy, [Winpilot](https://github.com/builtbybel/Winpilot/releases), a shot.

**Comment by christianbueno1** [comment]
[Hope this information helps you, and can update winget](https://github.com/microsoft/winget-cli/issues/3303#issuecomment-2131717653)
