### ISSUE TITLE
Remove Live captions and/or remove the hotkey

### ISSUE THREAD

**Issue by L1Q** [builtbybel/Winpilot#93]
One of my biggest gripes with W11 is that it look Win+Ctrl+L hotkey from me. I'm used to switching virtual desktops using Win+Ctrl+[HJKL], now L is taken away by an accessebility feature I will never need. Is there a way to remove it for good along with the hotkey? Any other software or command I can use to do it?

**Comment by Belim** [comment]
Not with Bloatynosy or its successor, [Winpilot](https://github.com/builtbybel/Winpilot/releases).
