### ISSUE TITLE
Get help button is now a dependency of some troubleshooters

### ISSUE THREAD

**Issue by Angeloxdd** [builtbybel/Winpilot#97]
You should let get help button untouched as default because this buttton is now a dependency from new troubleshooters.
Without this button you cannot run the new troubleshooters (because is happen all in the get help app). Another things are all great maybe the best  debloat and optimize tool.

**Comment by Belim** [comment]
Dont forget to give the successor to Bloatynosy, [Winpilot](https://github.com/builtbybel/Winpilot/releases), a shot.
